services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  librarywebapp_v2:
    build:
      context: .
      dockerfile: LibraryWebApp_v2/Dockerfile
    container_name: librarywebapp_v2
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
     ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=LibraryDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=false;"


volumes:
  sql_data:
